name: Cypress Tests
on:
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10 
    env:
      WORKING_DIR: ./E2E_tests
      CYPRESS_NO_COMMAND_LOG: 1  
      CYPRESS_VIDEO: false       

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: 'yarn'  

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: yarn install --frozen-lockfile --prefer-offline  

      - name: Run Cypress tests
        working-directory: ${{ env.WORKING_DIR }}
        run: yarn test  # Всё фильтры через test-runner.js